Add support for Apple Silicon processors
dscalzi/HeliosLauncher pull request #157
Opened 2021-04-06 12:52 UTC by GeekCornerGH

I saw we can build for new Apple Sillicon processors, so here you are @dscalzi

2021-04-07 10:32 UTC, DrDeee approved these changes

2021-04-07 16:27 UTC, dscalzi commented
What about the auto updater?

2021-04-07 16:36 UTC, dscalzi requested changes
Autoupdater needs to be addressed.

2021-04-08 06:21 UTC, GeekCornerGH commented
Oh yeah I forgot that

2021-04-08 09:10 UTC, GeekCornerGH commented
@dscalzi Enjoy 😁

2021-04-08 11:38 UTC, coeragames commented
As its working for ARM processors, will it work with Rasberry Pi and other computers working with an ARM architecture ?

2021-04-08 11:52 UTC, GeekCornerGH commented
No, because Minecraft Java is not supported on Raspberry

2021-04-10 07:34 UTC, GeekCornerGH commented
Also, lemme update Readme File

2021-04-10 07:38 UTC, GeekCornerGH commented
Ok, perfect 😁

2021-04-11 01:31 UTC, dscalzi commented on README.md
> +| macOS (Intel Processors) | `Helios-Launcher-setup-VERSION.dmg` |
wouldn't this be -x64?

2021-04-11 01:44 UTC, dscalzi commented on README.md
> +| macOS (Intel Processors) | `Helios-Launcher-setup-VERSION.dmg` |
I just checked the build output and it doesnt do -x64 for intel. This may be a problem for the autoupdater because its always looking for the arch. `https://github.com/dscalzi/HeliosLauncher/releases/download/v${info.version}/helioslauncher-setup-${info.version}-${process.arch}.dmg`

Is there a way you can get electron builder to put -x64 in the name? (without hardcoding it)

2021-04-11 07:19 UTC, GeekCornerGH commented on README.md
> +| macOS (Intel Processors) | `Helios-Launcher-setup-VERSION.dmg` |
Nope, there is no -x64 for intel

2021-04-11 07:23 UTC, GeekCornerGH commented on README.md
> +| macOS (Intel Processors) | `Helios-Launcher-setup-VERSION.dmg` |
> I just checked the build output and it doesnt do -x64 for intel. This may be a problem for the autoupdater because its always looking for the arch. `https://github.com/dscalzi/HeliosLauncher/releases/download/v${info.version}/helioslauncher-setup-${info.version}-${process.arch}.dmg`
> 
> Is there a way you can get electron builder to put -x64 in the name? (without hardcoding it)

Fixed in latest commit

2021-05-14 02:37 UTC, dscalzi commented
Thanks, landed in https://github.com/dscalzi/HeliosLauncher/commit/cd1ca7edf50160214476cf02ff1f255771eb1dc8

2021-05-14 02:37 UTC, closed without merging