fix: Launcher freeze
dscalzi/HeliosLauncher pull request #227
Opened 2022-05-23 11:11 UTC by GeekCornerGH

If you were opening the MS Login while in settings and close the window before finishing auth, the launcher throws an error. This patch fixes the issue

2022-05-23 13:45 UTC, dscalzi requested changes

2022-05-23 13:45 UTC, dscalzi commented on app/assets/js/scripts/settings.js
>                  let errorDesc = queryMap.error_description
just move the log statement down after the variables are initialized

2022-05-23 13:45 UTC, dscalzi commented on app/assets/js/scripts/settings.js
> +        if (Object.prototype.hasOwnProperty.call(queryMap, error)) {
? error is not defined anywhere

2022-05-24 03:25 UTC, GeekCornerGH commented on app/assets/js/scripts/settings.js
> +        if (Object.prototype.hasOwnProperty.call(queryMap, error)) {
For some reason it is?

2022-05-24 03:26 UTC, GeekCornerGH commented on app/assets/js/scripts/settings.js
>                  let errorDesc = queryMap.error_description
Alright

2022-12-10 04:49 UTC, dscalzi approved these changes

2022-12-10 04:49 UTC, merged