Launcher in French / Launcher en Français
dscalzi/HeliosLauncher pull request #318
Opened 2023-12-04 18:34 UTC by Vaxs02

I added and translated the en_US.toml file in French to make fr_FR.toml.

2023-12-04 20:11 UTC, dscalzi commented on app/assets/lang/fr_FR.toml
> +fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
still english

2023-12-04 20:11 UTC, dscalzi commented
@GeekCornerGH what do you think? I'm wondering if we should add french as well since most forks are french users.

2023-12-04 20:12 UTC, Vaxs02 commented
@GeekCornerGH stp dit oui

2023-12-05 07:05 UTC, GeekCornerGH commented
> @GeekCornerGH what do you think? I'm wondering if we should add french as well since most forks are french users.

That's a good question. I don't think adding i18n should be in the scope of the project, but it's your project, so do whatever you want

2023-12-24 17:07 UTC, GeekCornerGH requested changes
Review (biggest one I've ever done yet) is finally done, merry Christmas🎄🎉 
To be honest, there were quite some grammar mistakes, while some sentences weren't making sense at all. And I probably missed some.
Have you done the translation through Google Translate by any luck?

2024-01-19 02:13 UTC, sheazywi approved these changes

2024-02-23 09:24 UTC, Aeris1One commented on app/assets/lang/fr_FR.toml
> +checking = "Anylse les informations du système.."
Il y a une faute de frappe sur `Analyse`

2024-02-23 10:53 UTC, GeekCornerGH commented on app/assets/lang/fr_FR.toml
> +checking = "Anylse les informations du système.."
Thanks for the catch, fixed

2024-08-19 22:50 UTC, closed without merging